#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
  # set spacevim theme. by default colorscheme layer is not loaded,
  # if you want to use more colorscheme, please load the colorscheme
  # layer
  colorscheme = 'molokai'
  colorscheme_bg = 'dark'
  enable_guicolors = true
  statusline_separator = 'arrow'
  statusline_inactive_separator = 'arrow'
  buffer_index_type = 4
  enable_tabline_filetype_icon = true
  enable_statusline_mode = false
  filetree_direction = 'left'
  filemanager = "nerdtree"
  bootstrap_before = 'init#before'
  bootstrap_after = 'init#after'
  # enable_neomake = false
  # enable_ale = true
  lint_on_the_fly = true
  relativenumber = false
  lint_engine = 'ale'
  # lint_engine = 'syntastic'

[[custom_plugins]]
name = 'ryanoasis/vim-devicons'
merged = 0

[[custom_plugins]]
name = 'pangloss/vim-javascript'
merged = 0

[[custom_plugins]]
name = 'tyrannicaltoucan/vim-quantum'
merged = 0

[[custom_plugins]]
name = 'maxmellon/vim-jsx-pretty'
merged = 0

[[custom_plugins]]
name = 'tpope/vim-commentary'
merged = 0

[[custom_plugins]]
name = 'slim-template/vim-slim'
merged = 0

[[custom_plugins]]
name = 'elixir-editors/vim-elixir'
merged = 0

[[custom_plugins]]
name = 'amadeus/vim-mjml'
merged = 0

# Enable autocomplete layer
# [[layers]]
# name = 'autocomplete'
# auto-completion-return-key-behavior = 'complete'
# auto-completion-tab-key-behavior = 'smart'

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[layers]]
name = 'colorscheme'

[[layers]]
name = 'lang#typescript'

[[layers]]
name = 'lang#python'

[[layers]]
name = 'lang#php'

[[layers]]
name = 'tmux'

[[layers]]
name = "fzf"

# [[layers]]
# name = "checkers"
# show_cursor_error = true
# lint_on_the_fly = true
# lint_on_save = false
